# Generated by Django 4.0.1 on 2022-01-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
        migrations.AddField(
            model_name='author',
            name='articles',
            field=models.ManyToManyField(to='main.Article'),
        ),
    ]
