# Generated by Django 4.0.1 on 2022-01-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_article_authors_author_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(to='main.Author'),
        ),
    ]
